Repository lucasgmelo/cinema-management, pull requests merged in 2022-10, with the labels that each got.

#47 feat(live-update) update tickets total
  client/src/app/pages/checkout/checkout.component.html
  client/src/app/pages/checkout/checkout.component.ts
Labels: enhancement

#49 Card infos
  client/src/app/pages/add-movie/add-movie.component.html
  client/src/app/pages/checkout/checkout.component.scss
  client/src/app/pages/payment/payment.component.html
  client/src/app/pages/payment/payment.component.ts
  client/src/app/pages/signin/signin.component.html
  client/src/app/pages/signin/signin.component.scss
  client/src/app/pages/signup/signup.component.html
Labels: bug, enhancement

#51 feat(checkout page) seat numbers control
  client/src/app/pages/checkout/checkout.component.html
  client/src/app/pages/checkout/checkout.component.ts
Labels: enhancement

#52 feat card number
  client/src/app/pages/payment/payment.component.html
Labels: bug

#57 feat(checkout page) send tickets to backend
  client/src/app/pages/checkout/checkout.component.html
  client/src/app/pages/checkout/checkout.component.ts
  client/src/app/services/api/types.ts
Labels: enhancement

#60 checkout page fixes
  client/src/app/app-routing.module.ts
  client/src/app/pages/checkout/checkout.component.ts
  client/src/app/pages/movie/movie.component.ts
  client/src/app/services/api/api.service.ts
Labels: enhancement

#61 feat(checkout page) tickets show up on tickets page
  client/src/app/pages/tickets/tickets.component.ts
  client/src/app/services/api/api.service.ts
  server/repositories/ticketsRepositories.js
Labels: enhancement

#62 feat(ticket-pdf): update funcionalities
  client/src/app/components/ticket-card/ticket-card.component.html
  client/src/app/components/ticket-card/ticket-card.component.scss
  client/src/app/components/ticket-card/ticket-card.component.ts
  client/src/app/pages/tickets/tickets.component.ts
  package-lock.json
  server/controllers/moviesController.js
  server/routes.js
Labels: enhancement

#67 Delete button
  client/src/app/components/management-card/management-card.component.html
  client/src/app/components/management-card/management-card.component.ts
  client/src/app/pages/add-movie/add-movie.component.html
  client/src/app/pages/add-movie/add-movie.component.ts
  client/src/app/pages/management/management.component.html
  client/src/app/services/api/api.service.ts
  server/routes.js
Labels: enhancement

#69 feat(delete-button) routes bug fix
  client/src/app/pages/checkout/checkout.component.html
  client/src/app/pages/checkout/checkout.component.ts
  client/src/app/pages/payment/payment.component.ts
Labels: bug
